#!/bin/sh
# Lint every module in rtl/ on its own, so a warning has one obvious owner.
# Run before every push: it costs seconds and catches what a two-minute
# Quartus map would, without waiting for Quartus.
#
# The vendored cores are waived by rule and path. The waiver file is built
# here rather than committed, because Verilator rejects the whole file if it
# names a rule that version does not know -- which is how a waiver written
# against the newest Verilator broke the lint on CI's older one. Each rule is
# probed first and only the ones that exist go in.
set -e
here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/.." && pwd)
verilator --version >/dev/null 2>&1 || { echo "verilator not found" >&2; exit 2; }

PROBE=$(mktemp -d)
trap 'rm -rf "$PROBE"' EXIT
echo 'module lintprobe; endmodule' > "$PROBE/lintprobe.v"

RULES="ALWCOMBORDER BLKANDNBLK BLKSEQ CASEINCOMPLETE CASEOVERLAP CASEX CMPCONST
       COMBDLY ENUMVALUE EOFNEWLINE GENUNNAMED IMPLICIT INITIALDLY LATCH
       MULTIDRIVEN PINMISSING PROCASSINIT REALCVT SELRANGE SIDEEFFECT STMTDLY
       SYNCASYNCNET UNDRIVEN UNOPTFLAT UNSIGNED UNUSEDGENVAR VARHIDDEN
       WIDTHCONCAT WIDTHEXPAND WIDTHTRUNC ASCRANGE"
VENDOR='*/cpu-fx68k/* */cpu-tv80/* */sound-jt03/* */sound-jt49/*'
# the patterns are for Verilator, not the shell: without this the shell
# expands them into real paths and the waiver matches nothing
set -f

WAIVE="$PROBE/waivers.vlt"
{
  echo '`verilator_config'
  echo '// Generated by sim/lint.sh. The vendored cores are kept exactly as'
  echo '// upstream wrote them so they stay diffable; nothing under rtl/ is'
  echo '// waived, and a genuine dont-care there gets its own narrow lint_off'
  echo '// in the source with the reason on the line above it.'
  for r in $RULES; do
      verilator --lint-only "-Wno-$r" "$PROBE/lintprobe.v" >/dev/null 2>&1 || continue
      for f in $VENDOR; do
          echo "lint_off -rule $r -file \"$f\""
      done
  done
} > "$WAIVE"

set +f
OPTS="-Wall -Wno-DECLFILENAME -Wno-UNUSEDSIGNAL -Wno-TIMESCALEMOD"
for w in UNUSEDPARAM PINCONNECTEMPTY; do
    verilator --lint-only "-Wno-$w" "$PROBE/lintprobe.v" >/dev/null 2>&1 \
        && OPTS="$OPTS -Wno-$w"
done

fail=0
for f in "$root"/rtl/*.sv; do
    m=$(basename "$f" .sv)
    printf '%-20s ' "$m"
    out=$(verilator --lint-only $OPTS "$WAIVE" --top-module "$m" \
          "$root"/rtl/*.sv "$root"/modules/*/*.v "$root"/modules/*/*.sv 2>&1 \
          | grep -E '^%(Error|Warning)' | grep -v 'Exiting due to' || true)
    if [ -z "$out" ]; then echo ok
    else echo; echo "$out" | sed 's/^/    /'; fail=1
    fi
done

printf '%-20s ' "pocket memories"
out=$(verilator --lint-only $OPTS "$WAIVE" --top-module masterw_mem \
      "$root"/target/pocket/masterw_mem.sv "$root"/target/pocket/sdram_ctrl.sv \
      "$root"/target/pocket/sram_port.sv 2>&1 \
      | grep -E '^%(Error|Warning)' | grep -v 'Exiting due to' \
      | grep -v 'sdram_ctrl.sv' || true)
if [ -z "$out" ]; then echo ok
else echo; echo "$out" | sed 's/^/    /'; fail=1
fi

[ $fail = 0 ] || exit 1
echo "lint clean"
